#!/bin/bash
rm -rf src/autoincludes

# Postpositions.
mkdir -p src/adpositions/
cp /mnt/share/sam/proj/libpanini//tools/wals/repo//adpositions ./src/adpositions/postpositions
echo "(include adpositions/postpositions)" >> src/autoincludes
mkdir -p src/adpositions/
cp /mnt/share/sam/proj/libpanini//tools/wals/repo//adpositions ./src/adpositions/adpositions
echo "(include adpositions/adpositions)" >> src/autoincludes
